### ISSUE TITLE
possible bug with reported letter count

### ISSUE THREAD

**Issue by dtenenba** [lbenedetto/ChalkJotto#1]
The secret word was HOOKS. I guessed SHOOK and the game told me that I got 4 letters right. But I think it should have said 5. Every letter in SHOOK is in HOOKS.

I know that the tutorial says "duplicate letters do not count twice". However, I have seen the game give a result of 5 when you give it all the correct letters but in the wrong order (perhaps this is when the secret word does not contain any duplicate letters), so this seems inconsistent. When I have played the game on paper (with another person, each person has their own secret word and you take turns guessing) I would always give a 5 in this situation. It seems a little bit inconsistent.

If I received a 5 I would know that I just need to rearrange the letters, but because I received a 4 I kept looking for another letter until I had eliminated all possibilities.

I ended up giving up the game after guessing SHOOK and getting 4, because I had eliminated any other letter it could be. I will have to remember this weird quirk in the future.

This seems like a bug to me. Or maybe not. I think this should be a special case and always return 5.

App version 20.4.0
Android version 10 (build number QQ2A.200405.005)
Pixel 3

**Comment by lbenedetto** [comment]
First of all, thanks for taking the time to write to me about this. :)
I agree that it is confusing to see 4 matching letters when you've got 5
all the letters correct. I have some ideas on how to fix this:

1. Count duplicate letters twice (would make some types of deductions
impossible)
2. Only count duplicate letters twice if they are also duplicated in the
secret word (Might make things more confusing)
3. The secret word is not allowed to have duplicates (This is specified in
some rulesets for Jotto I found on Google)
4. Special case for anagrams.

I'm leaning towards 3 or 4, what do you think?

**Comment by dtenenba** [comment]
Thanks for your response.

I lean towards 4. I am definitely against 3, that would limit things too much. 
4 is the behavior that I intuitively expect, but maybe not all users will.

**Comment by lbenedetto** [comment]
Alright. I should have that out in the next couple of days.

**Comment by dtenenba** [comment]
Seems like this was fixed! I just got the "A" result when I guessed an anagram of the secret word.
